version: '3'

services:
  db-server:
    image: mysql:latest
    container_name: db-server
    expose:
      - "3306"
    volumes:
      - "data:/var/lib/mysql"
      - "data:/var/log/mysql"
      - "./mysql:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/log:/var/log/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  app:
    image: golang:1.10.4
    container_name: app
    ports:
      - "8888:8888"
    volumes:
      - "./app/vendor:/go/src/github.com"
      - "./app:/go/src/app"
    depends_on:
      - db-server
    working_dir: /go/src/app
    command: go run main.go

volumes:
  data:
